FROM almalinux:9
ENV HOME=/
RUN dnf --releasever=9 update -y
RUN dnf --releasever=9 install -y \
        rpm-build \
        redhat-rpm-config \
        rpmdevtools \
        cmake \
        gcc-c++ \
        tar \
        make \
        openssl-devel \
        zlib \
        zlib-devel \
        brotli-devel \
        ruby \
        ruby-devel \
        rubygem-rake \
        bison \
        automake \
        libtool \
        git

RUN dnf --releasever=9 --enablerepo crb install -y libuv-devel

RUN rpmdev-setuptree
RUN echo '%dist   .el9' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown -R root:root /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/h2o.spec
RUN tar -czf /tmp/h2o.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
