name: update

on:
  workflow_dispatch:
  schedule:
    - cron: "40 19 1 * *"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: generate
        uses: shogo82148/actions-github-app-token@v1
      - id: update
        name: update
        run: |
          ./scripts/update.sh
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: shogo82148/actions-commit-and-create-pr@v1
        with:
          github-token: ${{ steps.generate.outputs.token }}
          commit-message: bump h2o ${{ steps.update.outputs.latest-version }}
